# https://ansible.readthedocs.io/projects/builder/en/stable/definition/#version-3-format
---
version: 3

dependencies:
  ansible_core:
    package_pip: ansible-core==2.19.3 # https://pypi.org/project/ansible-core/
  ansible_runner:
    package_pip: ansible-runner
  galaxy: files/galaxy-requirements.txt
  python: files/requirements.txt
  system: files/bindep.txt

images:
  base_image:
    name: registry.access.redhat.com/ubi9/python-312

additional_build_files:
    - src: files/ansible.cfg
      dest: configs

additional_build_steps:
  prepend_base:
    - USER root
    - ENV TZ=Europe/Moscow
    - RUN pip install --upgrade pip

  prepend_galaxy:
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg

options:
    workdir: /runner
    user: 1001
